### ISSUE TITLE
Not able to run any command getting below error for dependency & tree as well.

### ISSUE THREAD

**Issue by rajendrasnagar** [baksale/sfdx-dependency-plugin#41]
Hi,

I have installed plugin & tried to execute commands as mentioned the the examples, but for all commands , i am getting below error.

![image](https://user-images.githubusercontent.com/3901703/82632253-50ad4380-9c15-11ea-867d-767d77faf486.png)

Regards,
Raj

**Comment by baksale** [comment]
Hi, could you try running without double quotes?
I'll be able to login tomorrow.

**Comment by baksale** [comment]
Should be fixed, please try now and comment.
Before test, please do:
`npm i -g sfdx-dependency-plugin` to update local version with fixes.

**Comment by baksale** [comment]
Closing as this is working, please confirm otherwise.
